name:                JuicyPixels-blurhash
version:             0.1.0.3
github:              "SamProtas/JuicyPixels-blurhash"
license:             BSD3
author:              "Sam Protas"
maintainer:          "sam.protas@gmail.com"
copyright:           "2020 Sam Protas"

extra-source-files:
- README.md
- ChangeLog.md
- docs/*
- imgs/*

extra-doc-files:
  - docs/*


# Metadata used when publishing your package
synopsis:            Blurhash is a very compact representation of a placeholder for an image
category:            Graphics, Image

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/SamProtas/JuicyPixels-blurhash#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.9 && < 0.11
- containers >= 0.4.2 && < 0.7
- filepath >= 1.4.1.1 && < 1.5
- JuicyPixels >= 3.2.8 && < 3.4
- vector >= 0.10 && < 0.13

library:
  source-dirs: src

executables:
  JuicyPixels-blurhash-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - JuicyPixels-blurhash
    - optparse-applicative >= 0.14.3 && < 0.18

tests:
  JuicyPixels-blurhash-test:
    main:                Spec.hs
    source-dirs:         test
    # https://github.com/google/proto-lens/commit/7fa4db0edb2a672d1fd2dcfa95853b1dbb80d2f9
    verbatim:
      other-modules:
        Blurhash
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - JuicyPixels-blurhash
    - hedgehog >= 1.0.2 && < 1.2
    - tasty >= 1.2.3 && < 1.5
    - tasty-discover >= 4.2.1 && < 4.3
    - tasty-hedgehog >= 1.0.0.2 && < 1.2
    - tasty-hunit >= 0.10.0.2 && < 0.11
  JuicyPixels-blurhash-doctests:
    main:                Main.hs
    source-dirs:         doctest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - JuicyPixels-blurhash
    - doctest >= 0.16.2 && < 0.20
    - Glob >= 0.10 && < 0.11
